/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author camil
 */
public class Vista_Actualizar extends javax.swing.JFrame {

    /**
     * Creates new form Vista_insertar
     */
    public Vista_Actualizar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_ID = new javax.swing.JLabel();
        Label_nombre = new javax.swing.JLabel();
        Label_nacionalidad = new javax.swing.JLabel();
        label_edad = new javax.swing.JLabel();
        jpanel_ = new javax.swing.JPanel();
        Botton_modificar = new javax.swing.JButton();
        Botton_cancelar = new javax.swing.JButton();
        Text_ID = new javax.swing.JTextField();
        text_nombre = new javax.swing.JTextField();
        Jtext_nacionalidad = new javax.swing.JTextField();
        text_edad = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar - Autores");

        label_ID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_ID.setText("ID");

        Label_nombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Label_nombre.setText("NOMBRE");

        Label_nacionalidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Label_nacionalidad.setText("NACIONALIDAD");

        label_edad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_edad.setText("EDAD");

        jpanel_.setBackground(new java.awt.Color(153, 152, 152));

        Botton_modificar.setBackground(new java.awt.Color(99, 198, 252));
        Botton_modificar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Botton_modificar.setText("Modificar");
        Botton_modificar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(4, 104, 191), 2));
        Botton_modificar.setPreferredSize(new java.awt.Dimension(80, 30));

        Botton_cancelar.setBackground(new java.awt.Color(99, 198, 252));
        Botton_cancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Botton_cancelar.setText("Cancelar");
        Botton_cancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(4, 104, 191), 2));
        Botton_cancelar.setPreferredSize(new java.awt.Dimension(80, 30));

        javax.swing.GroupLayout jpanel_Layout = new javax.swing.GroupLayout(jpanel_);
        jpanel_.setLayout(jpanel_Layout);
        jpanel_Layout.setHorizontalGroup(
            jpanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(Botton_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Botton_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanel_Layout.setVerticalGroup(
            jpanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addGroup(jpanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Botton_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Botton_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Text_ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        text_nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Jtext_nacionalidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        text_edad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanel_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_nombre)
                        .addGap(97, 97, 97)
                        .addComponent(text_nombre))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_nacionalidad)
                        .addGap(40, 40, 40)
                        .addComponent(Jtext_nacionalidad))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_ID)
                                .addGap(149, 149, 149)
                                .addComponent(Text_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_edad)
                                .addGap(123, 123, 123)
                                .addComponent(text_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 50, Short.MAX_VALUE)))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_ID)
                    .addComponent(Text_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_nombre)
                    .addComponent(text_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_nacionalidad)
                    .addComponent(Jtext_nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_edad)
                    .addComponent(text_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpanel_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_Actualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Botton_cancelar;
    public javax.swing.JButton Botton_modificar;
    public javax.swing.JTextField Jtext_nacionalidad;
    public javax.swing.JLabel Label_nacionalidad;
    public javax.swing.JLabel Label_nombre;
    public javax.swing.JTextField Text_ID;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jpanel_;
    public javax.swing.JLabel label_ID;
    public javax.swing.JLabel label_edad;
    public javax.swing.JTextField text_edad;
    public javax.swing.JTextField text_nombre;
    // End of variables declaration//GEN-END:variables
}
